name: Android Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build SMAC Android App
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 17
      # Required by the Android SDK command-line tools
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4. Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 5. Make Gradle executable
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # 6. Check Java
      - name: Check Java version
        run: java -version

      # 7. Check Gradle
      - name: Check Gradle version
        run: ./gradlew --version

